gui:
    scrollHeight: 2
    scrollPastBottom: true
    mouseEvents: true
    skipDiscardChangeWarning: false
    skipStashWarning: false
    sidePanelWidth: 0.2
    expandFocusedSidePanel: true
    mainPanelSplitMode: flexible
    theme:
        lightTheme: true
        activeBorderColor:
            - "#008700"
            - bold
        inactiveBorderColor:
            - black
        optionsTextColor:
            - "#0087af"
        selectedLineBgColor:
            - reverse
        selectedRangeBgColor:
            - reverse
        defaultFgColor:
            - black
    commitLength:
        show: true
    skipNoStagedFilesWarning: false
git:
    paging:
        colorArg: always
        pager: ""
        useConfig: true
    merging:
        manualCommit: false
        args: ""
    pull:
        mode: rebase
    skipHookPrefix: WIP
    autoFetch: true
    branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
    allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
    overrideGpg: false
    disableForcePushing: false
    commitPrefixes: {}
update:
    method: prompt
    days: 14
reporting: undetermined
splashUpdatesIndex: 0
confirmOnQuit: false
quitOnTopLevelReturn: true
keybinding:
    universal:
        quit: q
        # quit-alt1: <c-c>
        return: <esc>
        quitWithoutChangingDirectory: Q
        togglePanel: <tab>
        prevItem: <up>
        nextItem: <down>
        prevItem-alt: k
        nextItem-alt: j
        prevPage: ","
        nextPage: .
        gotoTop: <
        gotoBottom: ">"
        prevBlock: <left>
        nextBlock: <right>
        prevBlock-alt: h
        nextBlock-alt: l
        nextMatch: "n"
        prevMatch: "N"
        startSearch: /
        optionMenu: x
        optionMenu-alt1: "?"
        select: <space>
        goInto: <enter>
        confirm: <enter>
        confirm-alt1: "y"
        remove: d
        new: "n"
        edit: e
        openFile: o
        scrollUpMain: <pgup>
        scrollDownMain: <pgdown>
        scrollUpMain-alt1: K
        scrollDownMain-alt1: J
        scrollUpMain-alt2: <c-u>
        scrollDownMain-alt2: <c-d>
        executeCustomCommand: ":"
        createRebaseOptionsMenu: m
        pushFiles: P
        pullFiles: p
        refresh: R
        createPatchOptionsMenu: <c-p>
        nextTab: "]"
        prevTab: "["
        nextScreenMode: +
        prevScreenMode: _
        undo: z
        redo: <c-z>
        filteringMenu: <c-s>
        diffingMenu: W
        diffingMenu-alt: <c-e>
        copyToClipboard: <c-o>
        submitEditorText: <enter>
        appendNewline: <tab>
    status:
        checkForUpdate: u
        recentRepos: <enter>
        allBranchesLogGraph: a
    files:
        commitChanges: <c-c>
        commitChangesWithoutHook: w
        amendLastCommit: A
        commitChangesWithEditor: C
        ignoreFile: i
        refreshFiles: r
        stashAllChanges: s
        viewStashOptions: S
        toggleStagedAll: a
        viewResetOptions: D
        fetch: f
    branches:
        createPullRequest: o
        copyPullRequestURL: <c-y>
        checkoutBranchByName: c
        forceCheckoutBranch: F
        rebaseBranch: r
        renameBranch: R
        mergeIntoCurrentBranch: M
        viewGitFlowOptions: i
        fastForward: f
        pushTag: P
        setUpstream: u
        fetchRemote: f
    commits:
        squashDown: s
        renameCommit: r
        renameCommitWithEditor: R
        viewResetOptions: g
        markCommitAsFixup: f
        createFixupCommit: F
        squashAboveCommits: S
        moveDownCommit: <c-j>
        moveUpCommit: <c-k>
        amendToCommit: A
        pickCommit: p
        revertCommit: t
        cherryPickCopy: c
        cherryPickCopyRange: C
        pasteCommits: v
        tagCommit: T
        checkoutCommit: <space>
        resetCherryPick: <c-R>
        copyCommitMessageToClipboard: <c-y>
    stash:
        popStash: g
    commitFiles:
        checkoutCommitFile: c
    main:
        toggleDragSelect: v
        toggleDragSelect-alt: V
        toggleSelectHunk: a
        pickBothHunks: b
    submodules:
        init: i
        update: u
        bulkMenu: b
os:
    openCommand: sh -c "xdg-open {{filename}} >/dev/null"
    openLinkCommand: sh -c "xdg-open {{link}} >/dev/null"
disableStartupPopups: false
customCommands:
    - key: c
      context: "files"
      description: "commit files with Conventional Commits."
      prompts:
        - type: "menu"
          title: "What kind of commit type is it?"
          key: "Type"
          options:
            - name: "feat"
              description: "A new feature."
              value: "feat"
            - name: "fix"
              description: "A bug fix."
              value: "fix"
            - name: "docs"
              description: "Documentation only changes."
              value: "docs"
            - name: "style"
              description: "Changes that do not affect the meaning of the code."
              value: "style"
            - name: "refactor"
              description: "A code change that neither fixes a bug nor adds a feature."
              value: "refactor"
            - name: "pref"
              description: "A code change that improves perfomance."
              value: "pref"
            - name: "test"
              description: "Adding missing tests or correcting existing tests."
              value: "test"
            - name: "build"
              description: "Changes that affect the build system or external dependencies."
              value: "build"
            - name: "ci"
              description: "Changes to our CI configuration files and scripts."
              value: "ci"
            - name: "chore"
              description: "Other changes that don't modify src or test files."
              value: "chore"
            - name: "revert"
              description: "Reverts a previous commit."
              value: "revert"
            - name: "wip"
              description: "Work in Progress."
              value: "wip"
        - type: "input"
          title: "(Optional) Enter the scope."
          key: "Scope"
          initialValue: ""
        - type: "input"
          title: "Enter the Message."
          key: "Message"
          initialValue: ""
        - type: "menu"
          title: "Choise the emoji."
          key: "Emoji"
          options:
            - name: "(empty)"
              description: ""
              value: ""
            - name: ":art:"
              description: "Improve structure / format of the code."
              value: ":art:"
            - name: ":zap:"
              description: "Improve performance"
              value: ":zap:"
            - name: ":fire:"
              description: "Remove code or files."
              value: ":fire:"
            - name: ":bug:"
              description: "Fix a bug."
              value: ":bug:"
            - name: ":ambulance:"
              description: "Critical hotfix."
              value: ":ambulane:"
            - name: ":sparkles:"
              description: "Introduce new features."
              value: ":sparkles:"
            - name: ":memo:"
              description: "Add or update documentation."
              value: ":memo:"
            - name: ":rocket:"
              description: "Deploy stuff."
              value: ":rocket:"
            - name: ":lipstick:"
              description: "Add or update the UI and style files."
              value: ":lipstick:"
            - name: ":tada:"
              description: "Begin a project."
              value: ":tada:"
            - name: ":white_check_mark:"
              description: "Add, update, or pass tests."
              value: ":white_check_mark:"
            - name: ":lock:"
              description: "Fix security or privacy issues."
              value: ":lock:"
            - name: ":closed_lock_with_key:"
              description: "Add or update secrets."
              value: ":closed_lock_with_key:"
            - name: ":bookmark:"
              description: "Release / Version tags."
              value: ":bookmark:"
            - name: ":rotating_light:"
              description: "Fix compiler / linter warnings."
              value: ":rotating_light:"
            - name: ":construction:"
              description: "Work in progress."
              value: ":construction:"
            - name: ":green_heart:"
              description: "Fix CI Build."
              value: ":green_heart:"
            - name: ":arrow_down:"
              description: "Downgrade dependencies."
              value: ":arrow_down:"
            - name: ":arrow_up:"
              description: "Upgrade dependencies."
              value: ":arrow_up:"
            - name: ":pushpin:"
              description: "Pin dependencies to specific versions."
              value: ":pushpin:"
            - name: ":construction_worker:"
              description: "Add or update CI build system."
              value: ":construction_worker:"
            - name: ":chart_with_upwards_trend:"
              description: "Add or update analytics or track code."
              value: ":chart_with_upwards_trend:"
            - name: ":recycle:"
              description: "Refactor code"
              value: ":recycle:"
            - name: ":heavy_plus_sign:"
              description: "Add a dependency."
              value: ":heavy_plus_sign:"
            - name: ":heavy_minus_sign:"
              description: "Remove a dependency."
              value: ":heavy_minus_sign:"
            - name: ":wrench:"
              description: "Add or update configuration files."
              value: ":wrench:"
            - name: ":hammer:"
              description: "Add or update development scripts."
              value: ":hammer:"
            - name: ":globe_with_meridians:"
              description: "Internationalization and localization."
              value: ":globe_with_meridians:"
            - name: ":pencil2:"
              description: "Fix typos."
              value: ":pencil2:"
            - name: ":poop:"
              description: "Write bad code that needs to be improved."
              value: ":poop:"
            - name: ":rewind:"
              description: "Revert changes."
              value: ":rewind:"
            - name: ":twisted_rightwards_arrows:"
              description: "Merge branches."
              value: ":twisted_rightwards_arrows:"
            - name: ":package:"
              description: "Add or update compiled files or packages."
              value: ":package:"
            - name: ":alien:"
              description: "Update code due to external API changes."
              value: ":alien:"
            - name: ":truck:"
              description: "Move or rename resources (e.g.: files, paths, routes)."
              value: ":truck:"
            - name: ":page_facing_up:"
              description: "Add or update license."
              value: ":page_facing_up:"
            - name: ":boom:"
              description: "Introduce breaking changes."
              value: ":boom:"
            - name: ":bento:"
              description: "Add or update assets."
              value: ":bento:"
            - name: ":wheelchair:"
              description: "Improve accessibility."
              value: ":wheelchair:"
            - name: ":bulb:"
              description: "Add or update comments in source code."
              value: ":bulb:"
            - name: ":beers:"
              description: "Write code drunkenly."
              value: ":beers:"
            - name: ":speech_balloon:"
              description: "Add or update text and literals."
              value: ":speech_balloon:"
            - name: ":card_file_box:"
              description: "Add or update contributor(s)."
              value: ":card_file_box:"
            - name: ":children_crossing:"
              description: "Improve user experience / usability."
              value: ":children_crossing:"
            - name: ":building_construction:"
              description: "Make architectural changes."
              value: ":building_construction:"
            - name: ":iphone:"
              description: "Work on responsive design."
              value: ":iphone:"
            - name: ":clown_face:"
              description: "Mock things."
              value: ":clown_face:"
            - name: ":egg:"
              description: "Add or update an easter egg."
              value: ":egg:"
            - name: ":see_no_evil:"
              description: "Add or update a .gitignore file."
              value: ":see_no_evil:"
            - name: ":camera_flash:"
              description: "Add or update snapshots."
              value: ":camera_flash:"
            - name: ":alembic:"
              description: " Perform experiments."
              value: ":alembic:"
            - name: ":mag:"
              description: "Improve SEO."
              value: ":mag:"
            - name: ":label:"
              description: "Add or update types."
              value: ":label:"
            - name: ":seedling:"
              description: "Add or update seed files."
              value: ":seedling:"
            - name: ":triangular_flag_on_post:"
              description: "Add, update, or remove feature flags."
              value: ":triangular_flag_on_post:"
            - name: ":goal_net:"
              description: "Catch errors."
              value: ":goal_net:"
            - name: ":dizzy:"
              description: "Add or update animations and transitions."
              value: ":dizzy:"
            - name: ":wastebasket:"
              description: "Deprecate code that needs to be cleaned up."
              value: ":wastebasket:"
            - name: ":passport_control:"
              description: "Work on code related to authorization, roles and permissions."
              value: ":passport_control:"
            - name: ":adhesive_bandage:"
              description: "Simple fix for a non-critical issue."
              value: ":adhesive_bandage:"
            - name: ":monocle_face:"
              description: "Data exploration/inspection."
              value: ":monocle_face:"
            - name: ":coffin:"
              description: "Remove dead code."
              value: ":coffin:"
            - name: ":test_tube:"
              description: "Add a failing test."
              value: ":test_tube:"
            - name: ":necktie:"
              description: "Add or update business logic."
              value: ":necktie:"
            - name: ":stethoscope:"
              description: "Add or update healthcheck."
              value: ":stethoscope:"
            - name: ":bricks:"
              description: "Infrastructure related changes."
              value: ":bricks:"
            - name: ":technologist:"
              description: "Improve developer experience."
              value: ":technologist:"
            - name: ":money_with_wings:"
              description: "Add sponsorships or money related infrastructure."
              value: ":money_with_wings:"
            - name: ":thread:"
              description: "Add or update code related to multithreading or concurrency."
              value: ":thread:"
            - name: ":safety_vest:"
              description: "Add or update code related to validation."
              value: ":safety_vest:"
        - type: "confirm"
          title: "Commit"
          body: "Commit with the message '{{.Form.Type}}({{.Form.Scope}}): {{.Form.Message}}{{.Form.Emoji}}'. Is this okay?"
      command: 'bash -c ''type="{{.Form.Type}}"; scope="{{.Form.Scope}}"; message="{{.Form.Message}}"; emoji="{{.Form.Emoji}}"; commit_message="$type${scope:+($scope)}: $message $emoji"; git commit -m "$commit_message"'''
      loadingText: "Commiting..."
services: {}
notARepository: prompt
