local status, ib = pcall(require, 'indent_blankline')
if (not status) then return end

ib.setup {
  char = '│',
  space_char_blankline = ' ',
  use_treesitter = true,
  show_first_indent_level = false,
  show_trailing_blankline_indent = false,
  show_current_context = true,
  use_treesitter_scope = false,
  filetype_exclude = { 'startify' },
  context_patterns = {
    '^for',
    '^func',
    '^if',
    '^object',
    '^table',
    '^while',
    'argument_list',
    'arguments',
    'block',
    'catch_clause',
    'class',
    'dictionary',
    'do_block',
    'element',
    'else_clause',
    'except',
    'for',
    'function',
    'if_statement',
    'import_statement',
    'method',
    'object',
    'operation_type',
    'return',
    'table',
    'try',
    'try_statement',
    'tuple',
    'while',
    'with',
  }
}
