require("servers.lua_ls")
require("servers.pyright")
require("servers.bashls")
require("servers.ts_ls")
require("servers.gopls")
require("servers.clangd")
require("servers.tailwindcss")
require("servers.efm")

vim.lsp.enable({
	"lua_ls",
	"pyright",
	"bashls",
	"ts_ls",
	"gopls",
	"clangd",
	"efm",
	"tailwindcss",
})
